# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "lint"

on:
  pull_request:
  push:
    branches:
      - "main"
      - "renovate/*"

jobs:
  cs:
    name: "typescript"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18.18

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Coding Standard"
        run: "npm run lint"
